---
- name: Configure host.
  hosts: all
  become: yes

  vars_files:
    - default.config.yml

  roles:
    - geerlingguy.docker
    - rolehippie.starship

  pre_tasks:
    - name: Ensure the locale exists
      community.general.locale_gen:
        name: en_US.UTF-8
        state: present

    # https://stackoverflow.com/a/26399105/157811
    - name: get the username running the deploy
      become: false
      action: command whoami
      register: current_username

    - name: Set ansible_user fact
      ansible.builtin.set_fact:
        ansible_user: "{{ current_username.stdout }}"

    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"

    - name: Install required packages on Arch
      community.general.pacman:
        update_cache: true
        name: [
          'git', 'zip', 'unzip', 'base-devel', 'cmake', 'openssh', 'gnupg', 'curl', 'net-tools',
          'fish', 'vim', 'neovim', 'tmux', 'lazygit',
          'btop', 'fzf', 'bat', 'fd', 'eza', 'ripgrep', 'zoxide',

          'gtk-layer-shell',

          # dev envs
          'go', 'nodejs', 'npm',

          # apps
          'zed', 'ghostty', 'vlc', 'keyd',

          # Fonts
          'noto-fonts', 'noto-fonts-emoji', 'noto-fonts-extra', 'noto-fonts-cjk', 'ttf-font-awesome',
          'ttf-iosevka-nerd', 'ttf-iosevkaterm-nerd', 'ttf-ubuntu-mono-nerd', 'ttf-jetbrains-mono-nerd',
          'ttf-jetbrains-mono', 'wqy-zenhei', 'wqy-microhei',
        ]

        state: present

    - include_tasks: tasks/setup_aur.yml

    - name: Ensure directories exists.
      become: false
      file:
        path: "/home/{{ ansible_user }}/{{ item }}"
        recurse: yes
        state: directory

      with_items:
        - ".config"
        - ".local/share/applications"
        - ".local/bin"

    - name: Dot config git directory.
      stat:
        path: "/home/{{ ansible_user }}/.config/.git"
      register: dotconfig_git

  tasks:
    - name: Ensure required services are started and enabled
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: yes
        state: started
      loop:
        - sshd
        - keyd

    - name: Setup dotconfig
      become: false
      command: "{{ item }}"
      args:
        chdir: "/home/{{ ansible_user }}/.config"
      with_items:
        - "git init"
        - "git remote add origin https://github.com/harryxu/dotconfig.git"
        - "git fetch"
        - "git checkout origin/main -ft"
      when: not dotconfig_git.stat.exists

    - name: Change user shell to fish
      user:
        name: "{{ ansible_user }}"
        shell: /usr/bin/fish

    - name: Install aur packages.
      kewlfft.aur.aur:
        use: yay
        state: present
        name: [
          'google-chrome', 'visual-studio-code-bin', 'crow-translate',
        ]
      become: true
      become_user: aur_builder

    - name: Set custom environment variables in fish config
      ansible.builtin.copy:
        dest: "/home/{{ ansible_user }}/.config/fish/conf.d/custom.fish"
        content: |
          # Set the default browser for applications launched from this shell
          set -gx BROWSER 'google-chrome-stable'
        mode: '0664'
        force: false
      when: dotconfig_git.stat.exists

    - include_tasks: tasks/fcitx5.yml
    - include_tasks: tasks/ulauncher.yml
    - include_tasks: tasks/kde.yml

    - name: Check if extras.yml exists
      stat:
        path: "{{ playbook_dir }}/extras.yml"
      register: extras_file

    - name: Include extras.yml if it exists
      include_tasks: extras.yml
      when: extras_file.stat.exists
