---
- name: Configure host.
  hosts: all
  become: yes

  vars_files:
    - default.config.yml

  roles:
    - geerlingguy.docker
    - rolehippie.starship

  pre_tasks:
    - name: Ensure the locale exists
      community.general.locale_gen:
        name: en_US.UTF-8
        state: present

    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"

    - name: Install required packages on Arch
      community.general.pacman:
        update_cache: true
        name: [
          'git', 'vim', 'neovim', 'tmux', 'zip', 'unzip', 'base-devel', 'cmake',
          'openssh', 'fzf', 'gnupg', 'curl', 'net-tools', 'fish',

          # Fonts
          'noto-fonts', 'noto-fonts-emoji', 'noto-fonts-extra', 'noto-fonts-cjk', 'ttf-font-awesome',
          'wqy-zenhei', 'wqy-microhei', 'ttf-jetbrains-mono'
        ]

        state: present

    # - name: Install nerd fonts from AUR using yay
    #   become: yes
    #   become_user: your_username
    #   ansible.builtin.command: >
    #     yay -S --noconfirm nerd-fonts-iosevka nerd-fonts-iosevka-term nerd-fonts-ubuntu-mono nerd-fonts-jetbrains-mono
    #   args:
    #     creates: /usr/share/fonts/nerd-fonts/  # 可以用路径做简单幂等判断

    # https://stackoverflow.com/a/26399105/157811
    - name: get the username running the deploy
      become: false
      action: command whoami
      register: current_username

    - name: Ensure directories exists.
      become: false
      file:
        path: /home/{{ current_username.stdout }}/{{ item }}
        recurse: yes
        state: directory

      with_items:
        - ".config"
        - ".local/share/applications"
        - ".local/bin"

    - name: Dot config git directory.
      stat:
        path: /home/{{ current_username.stdout }}/.config/.git
      register: dotconfig_git

  tasks:

    - name: Enable and start sshd service
      ansible.builtin.systemd:
        name: sshd
        enabled: yes
        state: started

    # - name: Setup dotconfig
    #   become: false
    #   command: "{{ item }}"
    #   args:
    #     chdir: /home/{{ current_username.stdout }}/.config
    #   with_items:
    #     - "git init"
    #     - "git remote add origin git@github.com:harryxu/dotconfig.git"
    #     - "git fetch"
    #     - "git checkout origin/main -ft"
    #   when: not dotconfig_git.stat.exists

    - name: Change user shell to fish
      user:
        name: "{{ current_username.stdout }}"
        shell: /usr/bin/fish
